[package]
name = "cubing_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.41", features = ["serde"] }
csv = "1.3.1"
dotenv = "0.15.0"
mysql = "26.0.0"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"
